### ISSUE TITLE
Check ALL link responds 404

### ISSUE THREAD

**Issue by joelhandwell** [TheJambo/awesome-testing#1]
Maybe it's moved to somewhere else. I tried to find where it is now and found [this](https://chrome.google.com/webstore/detail/check-all/hcajloodonmplhncgandpgjgagckkdhn) It would be good to confirm if it is same extension originally included in this list.

**Comment by TheJambo** [comment]
That does appear to be the same one.

I've updated the list with your new link. Thanks!
