### ISSUE TITLE
Link to Check All broken

### ISSUE THREAD

**Issue by roesslerj** [TheJambo/awesome-testing#12]
I would fix it, but I am not sure where it was meant to point to...

**Comment by Prome88** [comment]
I would assume that it should point out to chrome extension which checks / unchecks all checkboxes on one website such as - https://chrome.google.com/webstore/detail/check-all/nnbihdpkeohjdfncchjhidbbonnihaob?hl=en .

But I would personally suggest using https://chrispederick.com/work/web-developer/ which has a lot more functions and is available for other browsers too.

**Comment by TheJambo** [comment]
Fixed the link to the one that @Prome88 suggested. :) Thanks for raising @roesslerj!
