### ISSUE TITLE
Add known tester's/testing blogs

### ISSUE THREAD

**Issue by filfreire** [TheJambo/awesome-testing#4]
Example:
James Bach - www.satisfice.com/blog/
Michael Bolton - http://www.developsense.com/blog/
Janet Gregory - http://janetgregory.ca/blog/
...
among many others.

**Comment by tob33** [comment]
@TheJambo Do you want to add a section for blogs?

**Comment by TheJambo** [comment]
:D I completely forgot. I'll ask http://testers.chat for recommendations and put them in along with @filfreire's suggestions.

**Comment by tob33** [comment]
There is a page about blogs on the MoT already that we could link to. https://www.ministryoftesting.com/testing-feeds/
