### ISSUE TITLE
Curated Lists

### ISSUE THREAD

**Issue by fbaptista** [TheJambo/awesome-testing#55]
Hello @TheJambo!

I've seen many comunity-based sources like https://github.com/atinfo/awesome-test-automation that are not accepting PRs and improvements over months. 

I am wondering if you are able to accept contributions to make your repo more complete in terms of testing tools and practices. 
There are several categorization and tools per stack that can be very useful to start contributing, like mobile testing, performance testing, chaos engineering and so on.

Let me know if you are open to it!

**Comment by TheJambo** [comment]
Hey @fbaptista - This isn't excluding automation at all, so if there's anything you'd like to add that falls under the umbrella of testing, go nuts!
